In [1]:
print("Hello World")

Hello World


In [3]:
# pip install numpy

import numpy as np
from numpy import doc

print(repr(np))

help(doc)

<module 'numpy' from '/Users/suren/MyFiles/OTUS/lessons/Python-Basic.2023.05/39.numpy/venv/lib/python3.11/site-packages/numpy/__init__.py'>
Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - constants
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    constants
    ufuncs

DATA
    __all__ = ['constants', 'ufuncs', '__doc__']

FILE
    /Users/suren/MyFiles/OTUS/lessons/Python-Basic.2023.05/39.numpy/venv/lib/python3.11/site-packages/numpy/doc/__init__.py




In [4]:
a = np.array([1, 2, 3])

In [5]:
a

array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [7]:
a = np.array([5, 7, 11, 13])
print(a)

[ 5  7 11 13]


In [8]:
print(a.dtype)

int64


In [9]:
a.shape

(4,)

In [10]:
a.ndim

1

In [11]:
b = np.array([
    [4, 5, 6],
    [7, 8, 9],
])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [12]:
print(b)

[[4 5 6]
 [7 8 9]]


In [13]:
list(b)

[array([4, 5, 6]), array([7, 8, 9])]

In [14]:
b.dtype

dtype('int64')

In [15]:
b.dtype = np.int16

In [16]:
b

array([[4, 0, 0, 0, 5, 0, 0, 0, 6, 0, 0, 0],
       [7, 0, 0, 0, 8, 0, 0, 0, 9, 0, 0, 0]], dtype=int16)

In [17]:
b.shape

(2, 12)

In [18]:
b = np.array([
    [1, 2, 3],
    [7, 8, 9],
], dtype=np.int16)
b

array([[1, 2, 3],
       [7, 8, 9]], dtype=int16)

In [19]:
print(b)

[[1 2 3]
 [7 8 9]]


In [20]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [21]:
2 ** 32

4294967296

In [22]:
2 ** 32 + 3

4294967299

In [23]:
a = np.array([2 ** 32 + 3])
a

array([4294967299])

In [24]:
a.dtype

dtype('int64')

In [25]:
a.dtype = np.int16

In [26]:
a

array([3, 0, 1, 0], dtype=int16)

In [27]:
a = np.arange(10, 110, 5)
a

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105])

In [28]:
a.shape

(20,)

In [29]:
a = a.reshape(4, 5)
a

array([[ 10,  15,  20,  25,  30],
       [ 35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80],
       [ 85,  90,  95, 100, 105]])

In [30]:
a.shape

(4, 5)

In [31]:
a = np.arange(10, 110, 5).reshape(4, 5)
a

array([[ 10,  15,  20,  25,  30],
       [ 35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80],
       [ 85,  90,  95, 100, 105]])

In [32]:
a[0]

array([10, 15, 20, 25, 30])

In [33]:
a[0][3]

25

In [34]:
a[0, 3]

25

In [35]:
c

array([0, 1, 2, 3, 4, 5])

In [36]:
c.fill(7)
c

array([7, 7, 7, 7, 7, 7])

In [37]:
c = np.empty(2)
c

array([2.05833592e-312, 2.33419537e-312])

In [38]:
np.empty(2, dtype=np.int8)

array([1, 1], dtype=int8)

In [39]:
np.empty(20, dtype=np.int16)

array([     0,      0,      0,  16368,      0,      0,      0,  16390,
            0,      0,      0,  16408,      0,      0, -32768,  16421,
            0,      0,      0,  16433], dtype=int16)

In [40]:
c

array([2.05833592e-312, 2.33419537e-312])

In [41]:
c.dtype

dtype('float64')

In [42]:
c.fill(1)
c

array([1., 1.])

In [43]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [44]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [45]:
a = np.linspace(1, 10, 5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [46]:
a.shape

(5,)

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
SIZE = 10
SHAPE = (SIZE, )

np.zeros(SHAPE)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
SIZE_X = 3
SIZE_Y = 4
SHAPE = (SIZE_X, SIZE_Y)

a = np.zeros(SHAPE)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
a.shape

(3, 4)

In [51]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
b = np.arange(20, 40, 2)
b

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [53]:
for a_i, b_i in zip(a, b):
    print(a_i + b_i)

21
24
27
30
33
36
39
42
45
48


In [54]:
a + b

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [55]:
SHAPE

(3, 4)

In [56]:
a = np.arange(1, 13, 1).reshape(SHAPE)
b = np.arange(10, 46, 3).reshape(SHAPE)

print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[10 13 16 19]
 [22 25 28 31]
 [34 37 40 43]]


In [57]:
print(a.shape)
print(b.shape)

(3, 4)
(3, 4)


In [58]:
a + b

array([[11, 15, 19, 23],
       [27, 31, 35, 39],
       [43, 47, 51, 55]])

In [59]:
b - a

array([[ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [60]:
a * b

array([[ 10,  26,  48,  76],
       [110, 150, 196, 248],
       [306, 370, 440, 516]])

In [61]:
b / a

array([[10.        ,  6.5       ,  5.33333333,  4.75      ],
       [ 4.4       ,  4.16666667,  4.        ,  3.875     ],
       [ 3.77777778,  3.7       ,  3.63636364,  3.58333333]])

In [62]:
# ValueError: operands could not be broadcast together with shapes (2,) (3,) 
np.arange(2) + np.arange(3)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [64]:
# ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 
np.arange(6).reshape((2, 3)) + np.arange(6).reshape((3, 2))

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [65]:
np.arange(6).reshape((2, 3)) * np.arange(6).reshape((3, 2))

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [66]:
b - a

array([[ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [67]:
b.diff(a)

AttributeError: 'numpy.ndarray' object has no attribute 'diff'

In [68]:
np.diff(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [69]:
np.diff(b)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [70]:
b

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [71]:
np.diff(b, axis=0)

array([[12, 12, 12, 12],
       [12, 12, 12, 12]])

In [72]:
c = np.array([1, 2, "qwerty"])
c

array(['1', '2', 'qwerty'], dtype='<U21')

In [73]:
c = np.array([1, 2, "qwerty", None])
c

array([1, 2, 'qwerty', None], dtype=object)

In [74]:
np.diff(b, axis=1)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [75]:
np.diff(np.array([1, 3, 3, 7, -1, 9, 8]))

array([ 2,  0,  4, -8, 10, -1])

In [76]:
c = np.array([1, 3, 3, 7, -1, 9, 8])
c

array([ 1,  3,  3,  7, -1,  9,  8])

In [77]:
np.sum(c)

30

In [78]:
b

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [79]:
np.sum(b, axis=0)

array([66, 75, 84, 93])

In [80]:
np.prod(b)

40823331028480000

In [81]:
np.prod(b, axis=1)

array([  39520,  477400, 2163760])

In [82]:
34 * 37 * 40 * 43

2163760

In [83]:
np.prod(b, axis=0)

array([ 7480, 12025, 17920, 25327])

In [84]:
np.linalg.det(b)

LinAlgError: Last 2 dimensions of the array must be square

In [85]:
m = np.arange(16).reshape((4, 4))
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [86]:
np.linalg.det(m)

-7.099748146989162e-30

In [87]:
m = np.array([
    [-4, -1, 2],
    [10, 4, -1],
    [8, 3, 1],
])
print(m)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [88]:
m.shape

(3, 3)

In [89]:
np.linalg.det(m)

-14.000000000000009

In [90]:
m.dtype

dtype('int64')

In [91]:
m = np.array([
    [-4, -1, 2],
    [10, 4, -1],
    [8, 3, 1],
], dtype=np.int16)
print(m)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [92]:
np.linalg.det(m)

-14.000000000000009

In [94]:
c

array([ 1,  3,  3,  7, -1,  9,  8])

In [95]:
b

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [97]:
b_t = b.transpose()
b_t

array([[10, 22, 34],
       [13, 25, 37],
       [16, 28, 40],
       [19, 31, 43]])

In [98]:
b_t.shape

(4, 3)

In [99]:
b.shape

(3, 4)

In [100]:
b.T

array([[10, 22, 34],
       [13, 25, 37],
       [16, 28, 40],
       [19, 31, 43]])

In [101]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
a > 7

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [103]:
m

array([[-4, -1,  2],
       [10,  4, -1],
       [ 8,  3,  1]], dtype=int16)

In [104]:
m < 4

array([[ True,  True,  True],
       [False, False,  True],
       [False,  True,  True]])

In [105]:
a == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [106]:
a == b

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [107]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
b

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [109]:
c

array([ 1,  3,  3,  7, -1,  9,  8])

In [112]:
c = np.arange(16, 40, 2).reshape(b.shape)
c

array([[16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [113]:
b == c

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [114]:
b > c

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [115]:
b

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [116]:
c

array([[16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [117]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [119]:
a[0]

10

In [120]:
a[9]

19

In [121]:
a[-1]

19

In [122]:
a[:5]

array([10, 11, 12, 13, 14])

In [123]:
a[6:]

array([16, 17, 18, 19])

In [124]:
a[3:7]

array([13, 14, 15, 16])

In [125]:
a[2:7:3]

array([12, 15])

In [126]:
a[3:8:2]

array([13, 15, 17])

In [127]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [128]:
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [129]:
nums = list(range(1, 10))
nums

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [131]:
nums[2:5]

[3, 4, 5]

In [132]:
nums[2:5] = [10, 11, 12]

In [133]:
nums

[1, 2, 10, 11, 12, 6, 7, 8, 9]

In [134]:
nums[3:7]

[11, 12, 6, 7]

In [135]:
nums[3:7] = [4, 2]

In [136]:
nums

[1, 2, 10, 4, 2, 8, 9]

In [137]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [138]:
a[3:6]

array([13, 14, 15])

In [139]:
a[3:6] = [42, 10]

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [140]:
a[3:6] = [42, 10, 11]

In [141]:
a

array([10, 11, 12, 42, 10, 11, 16, 17, 18, 19])

In [142]:
a[3:7] = 5
a

array([10, 11, 12,  5,  5,  5,  5, 17, 18, 19])

In [143]:
nums[4:6]

[2, 8]

In [144]:
nums

[1, 2, 10, 4, 2, 8, 9]

In [146]:
nums[4:6] = [1]
nums

[1, 2, 10, 4, 1, 9]

In [147]:
nums[4:6] = 1

TypeError: can only assign an iterable

In [148]:
SHAPE

(3, 4)

In [149]:
def func(x, y):
    return x * 10 + y

SHAPE = (4, 5)
a = np.fromfunction(func, SHAPE, dtype=np.int32)
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]], dtype=int32)

In [150]:
SHAPE_3D = (2, 4, 6)
a = np.arange(48).reshape(SHAPE_3D)
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [151]:
a[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [152]:
a.shape

(2, 4, 6)

In [153]:
a[0].shape

(4, 6)

In [154]:
a[0, 0]

array([0, 1, 2, 3, 4, 5])

In [155]:
a[0][0]

array([0, 1, 2, 3, 4, 5])

In [156]:
a[1, 3]

array([42, 43, 44, 45, 46, 47])

In [157]:
a.size

48

In [158]:
a.ndim

3

In [159]:
a.shape

(2, 4, 6)

In [160]:
a[0, 0, 5]

5

In [161]:
a[0, 1, 5]

11

In [162]:
a[0, :, 5]

array([ 5, 11, 17, 23])

In [163]:
a[:, :, 5]

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

In [164]:
a[..., 5]

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

In [165]:
...

Ellipsis

In [166]:
SHAPE_5D = tuple(range(2, 7))
print(SHAPE_5D)

(2, 3, 4, 5, 6)


In [167]:
a = np.empty(SHAPE_5D, dtype=np.int16)
a

array([[[[[     0,      0,      0,      0,     71,      0],
          [     0,      0, -19456,   7171,      1,      0],
          [  -819,   6912,      1,      0,  14241,   1092],
          [     1,      0,      1,      0,      0,      0],
          [    -1,     -1,     -1,     -1,     -1,     -1]],

         [[    -1,     -1, -16560,   1243,      1,      0],
          [     0,      0,     -1,     -1,   3436,   6913],
          [     1,      0,  14241,   1092,      1,      0],
          [     1,      0,      9,      0,      0,      0],
          [     0,      0,      1,      0,      0,      0]],

         [[-16560,   1243,      1,      0,     28,      0],
          [    -1,     -1,   3452,   6913,      1,      0],
          [ 14241,   1092,      1,      0,      1,      0],
          [    11,      0,     56,      0,      0,      0],
          [     0,      0,      0,      0,     10,      0]],

         [[     0,      0,     28,      0,     -1,     -1],
          [  3460,   6913,      1,

In [168]:
a[..., -1]

array([[[[   0,    0, 1092,    0,   -1],
         [   0, 6913,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [  -1, 1092,    0,    0,    0]],

        [[6913,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0]],

        [[   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0]]],


       [[[   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0]],

        [[   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0],
         [   0,    0,    0,    0,    0]],

        [[   0,    0,    0,    0,    0],
         [   0, 1195,    0, 1195,    0],
         [1192,    0, 1192,    0,    0],
         [   0,    0,    0,    0,    0]]]], d

In [169]:
a.size

720

In [170]:
a.ndim

5

In [171]:
a.shape

(2, 3, 4, 5, 6)

In [172]:
SHAPE_5D

(2, 3, 4, 5, 6)

In [173]:
a[1, ..., 3]

array([[[   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0]],

       [[   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0]],

       [[   0,    0,    0,    0,    0],
        [   0,    0, 1195,    0, 1192],
        [   0, 1192,    0, 1192,    0],
        [   0,    0,    0,    0,    0]]], dtype=int16)

In [174]:
a[1, :, :, :, 3]

array([[[   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0]],

       [[   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0]],

       [[   0,    0,    0,    0,    0],
        [   0,    0, 1195,    0, 1192],
        [   0, 1192,    0, 1192,    0],
        [   0,    0,    0,    0,    0]]], dtype=int16)

In [175]:
a[1, ..., 3:5]

array([[[[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      2],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]]],


       [[[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [  

In [176]:
a[1, ..., 3:-1]

array([[[[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      2],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]]],


       [[[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0],
         [     0,      0]],

        [[     0,      0],
         [  

In [177]:
b

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [178]:
c

array([[16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [179]:
b > c

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [180]:
np.all(b > c)

False

In [181]:
np.any(b > c)

True

In [182]:
np.any(b > c, axis=0)

array([ True,  True,  True,  True])

In [183]:
np.any(b > c, axis=1)

array([False,  True,  True])

In [184]:
np.all(b > c, axis=0)

array([False, False, False, False])

In [185]:
np.all(b > c, axis=1)

array([False, False,  True])

In [186]:
np.sort(a)

array([[[[[     0,      0,      0,      0,      0,     71],
          [-19456,      0,      0,      0,      1,   7171],
          [  -819,      0,      1,   1092,   6912,  14241],
          [     0,      0,      0,      0,      1,      1],
          [    -1,     -1,     -1,     -1,     -1,     -1]],

         [[-16560,     -1,     -1,      0,      1,   1243],
          [    -1,     -1,      0,      0,   3436,   6913],
          [     0,      0,      1,      1,   1092,  14241],
          [     0,      0,      0,      0,      1,      9],
          [     0,      0,      0,      0,      0,      1]],

         [[-16560,      0,      0,      1,     28,   1243],
          [    -1,     -1,      0,      1,   3452,   6913],
          [     0,      0,      1,      1,   1092,  14241],
          [     0,      0,      0,      0,     11,     56],
          [     0,      0,      0,      0,      0,     10]],

         [[    -1,     -1,      0,      0,      0,     28],
          [     0,      1,   1092,

In [187]:
np.sort(b)

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [188]:
b

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [189]:
np.sort(b, axis=1)

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [190]:
np.sort(b, axis=0)

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [191]:
m

array([[-4, -1,  2],
       [10,  4, -1],
       [ 8,  3,  1]], dtype=int16)

In [192]:
np.sort(m)

array([[-4, -1,  2],
       [-1,  4, 10],
       [ 1,  3,  8]], dtype=int16)

In [193]:
np.sort(m, axis=0)

array([[-4, -1, -1],
       [ 8,  3,  1],
       [10,  4,  2]], dtype=int16)

In [194]:
m

array([[-4, -1,  2],
       [10,  4, -1],
       [ 8,  3,  1]], dtype=int16)

In [195]:
np.median(m)

2.0

In [196]:
np.average(m)

2.4444444444444446

In [197]:
np.median(a)

0.0

In [198]:
np.average(a)

-2.8069444444444445

In [199]:
np.mean(m)

2.4444444444444446