In [1]:
import numpy as np
from numpy import doc

help(doc)

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - basics
    - broadcasting
    - byteswapping
    - constants
    - creation
    - dispatch
    - glossary
    - indexing
    - internals
    - misc
    - structured_arrays
    - subclassing
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    basics
    broadcasting
    byteswapping
    constants
    creation
    dispatch
    glossary
    indexing
    internals
    misc
    structured_arrays
    subclassing
    ufuncs

DATA
    __all__ = ['basics', 'broadcasting', 'byteswapping', 'constants', 'cre...

FILE
    /home/suren/Documents/Otus/lessons/PythonBasic.2020-07/15.numpy/venv/lib/python3.8/site-packages/numpy/doc/__init__.py




In [2]:
np.array

<function numpy.array>

In [3]:
a = np.array([1, 2, 3])
print(repr(a))
print(type(a))

array([1, 2, 3])
<class 'numpy.ndarray'>


In [4]:
print(a.ndim)
print(a.shape)

1
(3,)


In [5]:
a.dtype

dtype('int64')

In [6]:
a.itemsize

8

In [7]:
b = np.array([[4, 5, 6], [7, 8, 9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [8]:
print(b.size)
print(b.ndim)
print(b.shape)

6
2
(2, 3)


In [9]:
print(repr(b.dtype))
print(b.dtype.name)
b.dtype = np.int32
print(b.dtype)
print(b.itemsize)

dtype('int64')
int64
int32
4


In [10]:
a = np.arange(15)
print(a)
a = a.reshape(3, 5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
b = np.arange(15, 115, 5).reshape(4, 5)
print(b)

[[ 15  20  25  30  35]
 [ 40  45  50  55  60]
 [ 65  70  75  80  85]
 [ 90  95 100 105 110]]


In [12]:
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(4, 5)
2
20
int64


In [13]:
a = np.arange(1, 5, 0.5)
print(a)
print(a.size)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
8


In [14]:
a = np.arange(0, 2, 0.3)
print(a)
print(a.size)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]
7


In [15]:
a = np.linspace(0, 6, 20)
a

array([0.        , 0.31578947, 0.63157895, 0.94736842, 1.26315789,
       1.57894737, 1.89473684, 2.21052632, 2.52631579, 2.84210526,
       3.15789474, 3.47368421, 3.78947368, 4.10526316, 4.42105263,
       4.73684211, 5.05263158, 5.36842105, 5.68421053, 6.        ])

In [16]:
a = np.arange(10)
b = np.arange(10, 20)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [17]:
SIZE = 10
SHAPE = (SIZE, )

res = np.zeros(SHAPE)
res

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
res.dtype

dtype('float64')

In [19]:
res = np.zeros(SHAPE, dtype=a.dtype)
res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
print(res.dtype)

int64


In [21]:
for i in range(SIZE):
    res[i] = a[i] + b[i]

res

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [22]:
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [24]:
SHAPE = 2, 3
a = np.arange(1, 7).reshape(SHAPE)
b = np.arange(9, 15).reshape(SHAPE)

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [25]:
a * b

array([[ 9, 20, 33],
       [48, 65, 84]])

In [26]:
b - a

array([[8, 8, 8],
       [8, 8, 8]])

In [27]:
a = np.arange(7)
b = np.arange(9)

# expected exception
# a + b

In [28]:
np.arange(10, 20) / np.arange(10)

<ipython-input-1-c0b5946fc56e>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.arange(10, 20) / np.arange(10)


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111])

In [29]:
a = np.arange(10)
print(a)
np.diff(a)

[0 1 2 3 4 5 6 7 8 9]


array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
a = np.arange(10, 50, 5).reshape(2, 4)
print(a)
np.diff(a)

[[10 15 20 25]
 [30 35 40 45]]


array([[5, 5, 5],
       [5, 5, 5]])

In [31]:
a * 3

array([[ 30,  45,  60,  75],
       [ 90, 105, 120, 135]])

In [32]:
np.diff(a * 4)

array([[20, 20, 20],
       [20, 20, 20]])

In [33]:
np.sum(a)

220

In [34]:
np.sum(a * 3)

660

In [35]:
a.ndim

2

In [36]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [37]:
np.sum(a, axis=0)

array([40, 50, 60, 70])

In [38]:
np.sum(a, axis=1)

array([ 70, 150])

In [39]:
np.prod(a)

141750000000

In [40]:
np.prod(a, axis=0)

array([ 300,  525,  800, 1125])

In [41]:
np.prod(a, axis=1)

array([  75000, 1890000])

In [42]:
a ** 2

array([[ 100,  225,  400,  625],
       [ 900, 1225, 1600, 2025]])

In [43]:
np.sqrt(a)

array([[3.16227766, 3.87298335, 4.47213595, 5.        ],
       [5.47722558, 5.91607978, 6.32455532, 6.70820393]])

In [44]:
a > 30

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [45]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [46]:
b = np.linspace(40, 75, 8, dtype=np.int64).reshape(2, 4)
b

array([[40, 45, 50, 55],
       [60, 65, 70, 75]])

In [47]:
a < b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [48]:
b = np.arange(50, 10, -5).reshape(2, 4)
b

array([[50, 45, 40, 35],
       [30, 25, 20, 15]])

In [49]:
a > b

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [50]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [51]:
a.dtype

dtype('int64')

In [52]:
a / 3

array([[ 3.33333333,  5.        ,  6.66666667,  8.33333333],
       [10.        , 11.66666667, 13.33333333, 15.        ]])

In [53]:
(a / 3) >= b

array([[False, False, False, False],
       [False, False, False,  True]])

In [54]:
a // 3

array([[ 3,  5,  6,  8],
       [10, 11, 13, 15]])

In [55]:
a // b

array([[0, 0, 0, 0],
       [1, 1, 2, 3]])

In [56]:
a % b

array([[10, 15, 20, 25],
       [ 0, 10,  0,  0]])

In [57]:
print(a)
print(b)

[[10 15 20 25]
 [30 35 40 45]]
[[50 45 40 35]
 [30 25 20 15]]


In [58]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [59]:
a[8]

512

In [60]:
a[2:5]

array([ 8, 27, 64])

In [61]:
a[:4]

array([ 0,  1,  8, 27])

In [62]:
a[7:]

array([343, 512, 729])

In [63]:
a[3:9:2]

array([ 27, 125, 343])

In [64]:
a[3::2]

array([ 27, 125, 343, 729])

In [65]:
a[::3]

array([  0,  27, 216, 729])

In [66]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [67]:
a[:9:3]

array([  0,  27, 216])

In [68]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [69]:
a[:9:3] = 123
a

array([123,   1,   8, 123,  64, 125, 123, 343, 512, 729])

In [70]:
SHAPE = 5, 4

b = np.arange(20).reshape(SHAPE)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [71]:
def f(x, y):
    print(x)
    print(y)
    return 10 * x + y

print(f(3, 4))

3
4
34


In [72]:
np.fromfunction(f, SHAPE)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [73]:
def inc_by_index_1(x):
    # 0, 1, 2, 3, 4
    # 0, 1, 3, 6, 10
    # print(x)
    if not (x > 0):
        return x
    return x + inc_by_index_1(x - 1)

print(inc_by_index_1(1))
print(inc_by_index_1(2))
print(inc_by_index_1(3))

1
3
6


In [74]:
a = np.arange(20, 60, 2).reshape(5, 4)
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [75]:
a[1]

array([28, 30, 32, 34])

In [76]:
a[3]

array([44, 46, 48, 50])

In [77]:
a[4][0]

52

In [78]:
a[4, 0]

52

In [79]:
a[:, 3]

array([26, 34, 42, 50, 58])

In [80]:
a[1:3, :2]

array([[28, 30],
       [36, 38]])

In [81]:
a[-1]

array([52, 54, 56, 58])

In [82]:
a[::-1]

array([[52, 54, 56, 58],
       [44, 46, 48, 50],
       [36, 38, 40, 42],
       [28, 30, 32, 34],
       [20, 22, 24, 26]])

In [83]:
a[::-1, ::-1]

array([[58, 56, 54, 52],
       [50, 48, 46, 44],
       [42, 40, 38, 36],
       [34, 32, 30, 28],
       [26, 24, 22, 20]])

In [84]:
a.transpose()

array([[20, 28, 36, 44, 52],
       [22, 30, 38, 46, 54],
       [24, 32, 40, 48, 56],
       [26, 34, 42, 50, 58]])

In [85]:
a

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [86]:
a_t = a.transpose()
a_t

array([[20, 28, 36, 44, 52],
       [22, 30, 38, 46, 54],
       [24, 32, 40, 48, 56],
       [26, 34, 42, 50, 58]])

In [87]:
print(a[0])
print(a_t[0])

[20 22 24 26]
[20 28 36 44 52]


In [88]:
print(a[:, 0])

[20 28 36 44 52]


In [89]:
SHAPE_3D = (2, 4, 6)

a = np.arange(48).reshape(SHAPE_3D)
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [90]:
print(a.ndim)
print(a.size)
print(a.shape)

3
48
(2, 4, 6)


In [91]:
print(a[1])
print(a[:, 3])
print(a[:, :, 5])

[[24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]
[[18 19 20 21 22 23]
 [42 43 44 45 46 47]]
[[ 5 11 17 23]
 [29 35 41 47]]


In [92]:
a[1, 3, 5]

47

In [93]:
a[..., 5]

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

In [94]:
a ** 5

array([[[        0,         1,        32,       243,      1024,
              3125],
        [     7776,     16807,     32768,     59049,    100000,
            161051],
        [   248832,    371293,    537824,    759375,   1048576,
           1419857],
        [  1889568,   2476099,   3200000,   4084101,   5153632,
           6436343]],

       [[  7962624,   9765625,  11881376,  14348907,  17210368,
          20511149],
        [ 24300000,  28629151,  33554432,  39135393,  45435424,
          52521875],
        [ 60466176,  69343957,  79235168,  90224199, 102400000,
         115856201],
        [130691232, 147008443, 164916224, 184528125, 205962976,
         229345007]]])

In [95]:
SHAPE_5D = tuple(range(2, 7))
SHAPE_5D

(2, 3, 4, 5, 6)

In [96]:
d = np.empty(SHAPE_5D, dtype=np.int16)
d

array([[[[[ 28992,  10594,  32710,      0,  28992,  10594],
          [ 32710,      0,  30096,    393,      0,      0],
          [ 30096,    393,      0,      0,  -6232,  -2224],
          [ 32709,      0,     11,      0,     -1,     -1],
          [     0,      0,      0,      0,      8,      0]],

         [[     0,      0,      0,      0,  32709,      0],
          [     0,      0,      0,      0,      9,      0],
          [     0,      0, -28831,  -2224,  32709,      0],
          [  4636,    344,      0,      0,     -1,     -1],
          [    -1,     -1,      0,      0,      0,      0]],

         [[    -1,     -1,     -1,     -1,      0,      0],
          [     0,      0,      1,      0,  32709,      0],
          [    72,      0,      0,      0,     11,      0],
          [     0,      0, -28831,  -2224,  32709,      0],
          [  4652,    344,      0,      0,      1,      0]],

         [[     0,      0,     28,      0,      0,      0],
          [    -1,     -1,     -1,

In [97]:
d[1, :, :, :, 5]

array([[[-2224,     0,     0,     0,    -1],
        [    0, -2224,     0,     0,     0],
        [    0,     0, -2224,     0,  7173],
        [    0,     0,     0,  7173,     0]],

       [[    0,     0,     0,     0,  7173],
        [    0,     0,     0,   339,     0],
        [ 7173,     0,     0,     0, 10594],
        [    0,     0,     0, -2225,     0]],

       [[-2225,     0,  9253,     0, -2225],
        [    0, -2225,     0, -2225,     0],
        [-2225,     0, -2225,     0, -2225],
        [    0, -2224,     0, -2224,     0]]], dtype=int16)

In [98]:
d[1, ..., 5]

array([[[-2224,     0,     0,     0,    -1],
        [    0, -2224,     0,     0,     0],
        [    0,     0, -2224,     0,  7173],
        [    0,     0,     0,  7173,     0]],

       [[    0,     0,     0,     0,  7173],
        [    0,     0,     0,   339,     0],
        [ 7173,     0,     0,     0, 10594],
        [    0,     0,     0, -2225,     0]],

       [[-2225,     0,  9253,     0, -2225],
        [    0, -2225,     0, -2225,     0],
        [-2225,     0, -2225,     0, -2225],
        [    0, -2224,     0, -2224,     0]]], dtype=int16)

In [99]:
print(d.shape)
print((d[1, ..., 5]).shape)

(2, 3, 4, 5, 6)
(3, 4, 5)


In [100]:
d[..., 4, 5]

array([[[    0,     0,     0,     0],
        [    0,     0,     0,     0],
        [    0,     0,     0,     0]],

       [[   -1,     0,  7173,     0],
        [ 7173,     0, 10594,     0],
        [-2225,     0, -2225,     0]]], dtype=int16)

In [101]:
from numpy import linalg


a = np.arange(18).reshape((2,3,3))
print(a)

print(linalg.det(a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[0. 0.]
