In [1]:
import numpy as np
from numpy import doc

help(doc)

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - basics
    - broadcasting
    - byteswapping
    - constants
    - creation
    - dispatch
    - glossary
    - indexing
    - internals
    - misc
    - structured_arrays
    - subclassing
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    basics
    broadcasting
    byteswapping
    constants
    creation
    dispatch
    glossary
    indexing
    internals
    misc
    structured_arrays
    subclassing
    ufuncs

DATA
    __all__ = ['basics', 'broadcasting', 'byteswapping', 'constants', 'cre...

FILE
    /home/suren/Documents/Otus/lessons/PythonBasic.2020-07/15.numpy/venv/lib/python3.8/site-packages/numpy/doc/__init__.py




In [2]:
np.array

<function numpy.array>

In [3]:
a = np.array([1, 2, 3])
print(repr(a))
print(type(a))

array([1, 2, 3])
<class 'numpy.ndarray'>


In [4]:
print(a.ndim)
print(a.shape)

1
(3,)


In [5]:
a.dtype

dtype('int64')

In [6]:
a.itemsize

8

In [7]:
b = np.array([[4, 5, 6], [7, 8, 9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [8]:
print(b.size)
print(b.ndim)
print(b.shape)

6
2
(2, 3)


In [9]:
print(repr(b.dtype))
print(b.dtype.name)
b.dtype = np.int32
print(b.dtype)
print(b.itemsize)

dtype('int64')
int64
int32
4


In [10]:
a = np.arange(15)
print(a)
a = a.reshape(3, 5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
b = np.arange(15, 115, 5).reshape(4, 5)
print(b)

[[ 15  20  25  30  35]
 [ 40  45  50  55  60]
 [ 65  70  75  80  85]
 [ 90  95 100 105 110]]


In [12]:
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(4, 5)
2
20
int64


In [13]:
a = np.arange(1, 5, 0.5)
print(a)
print(a.size)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
8


In [14]:
a = np.arange(0, 2, 0.3)
print(a)
print(a.size)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]
7


In [15]:
a = np.linspace(0, 6, 20)
a

array([0.        , 0.31578947, 0.63157895, 0.94736842, 1.26315789,
       1.57894737, 1.89473684, 2.21052632, 2.52631579, 2.84210526,
       3.15789474, 3.47368421, 3.78947368, 4.10526316, 4.42105263,
       4.73684211, 5.05263158, 5.36842105, 5.68421053, 6.        ])

In [16]:
a = np.arange(10)
b = np.arange(10, 20)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [17]:
SIZE = 10
SHAPE = (SIZE, )

res = np.zeros(SHAPE)
res

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
res.dtype

dtype('float64')

In [19]:
res = np.zeros(SHAPE, dtype=a.dtype)
res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
print(res.dtype)

int64


In [21]:
for i in range(SIZE):
    res[i] = a[i] + b[i]

res

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [22]:
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [24]:
SHAPE = 2, 3
a = np.arange(1, 7).reshape(SHAPE)
b = np.arange(9, 15).reshape(SHAPE)

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [25]:
a * b

array([[ 9, 20, 33],
       [48, 65, 84]])

In [26]:
b - a

array([[8, 8, 8],
       [8, 8, 8]])

In [27]:
a = np.arange(7)
b = np.arange(9)

# expected exception
# a + b

ValueError: operands could not be broadcast together with shapes (7,) (9,) 

In [ ]:
np.arange(10, 20) / np.arange(10)

In [ ]:
a = np.arange(10)
print(a)
np.diff(a)

In [ ]:
a = np.arange(10, 50, 5).reshape(2, 4)
print(a)
np.diff(a)

In [ ]:
a * 3

In [ ]:
np.diff(a * 4)

In [ ]:
np.sum(a)

In [ ]:
np.sum(a * 3)

In [ ]:
a.ndim

In [ ]:
a

In [ ]:
np.sum(a, axis=0)

In [ ]:
np.sum(a, axis=1)

In [ ]:
np.prod(a)

In [ ]:
np.prod(a, axis=0)

In [ ]:
np.prod(a, axis=1)

In [ ]:
a ** 2

In [ ]:
np.sqrt(a)

In [ ]:
a > 30

In [ ]:
a

In [ ]:
b = np.linspace(40, 75, 8, dtype=np.int64).reshape(2, 4)
b

In [ ]:
a < b

In [ ]:
b = np.arange(50, 10, -5).reshape(2, 4)
b

In [ ]:
a > b

In [ ]:
a

In [ ]:
a.dtype

In [ ]:
a / 3

In [ ]:
(a / 3) >= b

In [ ]:
a // 3

In [ ]:
a // b

In [ ]:
a % b

In [ ]:
print(a)
print(b)

In [ ]:
a = np.arange(10) ** 3
a

In [ ]:
a[8]

In [ ]:
a[2:5]

In [ ]:
a[:4]

In [ ]:
a[7:]

In [ ]:
a[3:9:2]

In [ ]:
a[3::2]

In [ ]:
a[::3]

In [ ]:
a[::-1]

In [ ]:
a[:9:3]

In [ ]:
a

In [ ]:
a[:9:3] = 123
a

In [ ]:
SHAPE = 5, 4

b = np.arange(20).reshape(SHAPE)
b

In [ ]:
def f(x, y):
    print(x)
    print(y)
    return 10 * x + y

print(f(3, 4))

In [ ]:
np.fromfunction(f, SHAPE)

In [ ]:
def inc_by_index_1(x):
    # 0, 1, 2, 3, 4
    # 0, 1, 3, 6, 10
    # print(x)
    if not (x > 0):
        return x
    return x + inc_by_index_1(x - 1)

print(inc_by_index_1(1))
print(inc_by_index_1(2))
print(inc_by_index_1(3))

In [ ]:
a = np.arange(20, 60, 2).reshape(5, 4)
a

In [ ]:
a[1]

In [ ]:
a[3]

In [ ]:
a[4][0]

In [ ]:
a[4, 0]

In [ ]:
a[:, 3]

In [ ]:
a[1:3, :2]

In [ ]:
a[-1]

In [ ]:
a[::-1]

In [ ]:
a[::-1, ::-1]

In [ ]:
a.transpose()

In [ ]:
a

In [ ]:
a_t = a.transpose()
a_t

In [ ]:
print(a[0])
print(a_t[0])

In [ ]:
print(a[:, 0])

In [ ]:
SHAPE_3D = (2, 4, 6)

a = np.arange(48).reshape(SHAPE_3D)
a

In [ ]:
print(a.ndim)
print(a.size)
print(a.shape)

In [ ]:
print(a[1])
print(a[:, 3])
print(a[:, :, 5])

In [ ]:
a[1, 3, 5]

In [ ]:
a[..., 5]

In [ ]:
a ** 5

In [ ]:
SHAPE_5D = tuple(range(2, 7))
SHAPE_5D

In [ ]:
d = np.empty(SHAPE_5D, dtype=np.int16)
d

In [ ]:
d[1, :, :, :, 5]

In [ ]:
d[1, ..., 5]

In [ ]:
print(d.shape)
print((d[1, ..., 5]).shape)

In [ ]:
d[..., 4, 5]

In [ ]:
from numpy import linalg


a = np.arange(18).reshape((2,3,3))
print(a)

print(linalg.det(a))