pip install numpy

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [7]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.random.random(5)

array([0.05574139, 0.36415461, 0.0146302 , 0.52599944, 0.97801303])

In [14]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [15]:
np.arange(10, 31, 5)

array([10, 15, 20, 25, 30])

In [16]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
array_zeros = np.zeros([4, 3, 2])

In [20]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [21]:
array1.ndim

2

In [23]:
array_zeros.ndim

3

In [24]:
array1.shape

(3, 3)

In [25]:
array_zeros.shape

(4, 3, 2)

In [26]:
array1.size

9

In [27]:
array_zeros.size

24

In [28]:
array1.

dtype('int64')

In [29]:
array_zeros.dtype

dtype('float64')

In [31]:
a1 = np.array([1, 2, 3])

In [32]:
a2 = np.array([10, 20, 30])

In [33]:
a1 + a2

array([11, 22, 33])

In [34]:
a1 - a2

array([ -9, -18, -27])

In [35]:
a1 * a2

array([10, 40, 90])

In [36]:
a1 / a2

array([0.1, 0.1, 0.1])

In [37]:
a1 * 2

array([2, 4, 6])

In [38]:
a1 / 2

array([0.5, 1. , 1.5])

In [39]:
a3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a3[2]

3

In [42]:
a3[-1]

9

In [43]:
a3[0:2]

array([1, 2])

In [44]:
a3[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [45]:
a3.min()

1

In [46]:
a3.max()

9

In [47]:
a3.sum()

45

In [48]:
a3.mean()

5.0

In [49]:
a3.prod()

362880

In [50]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [51]:
array2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [52]:
array1 + array2

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [53]:
array2 - array1

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [54]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
array3 = np.array([[10, 20, 30, 45], [40, 50, 60, 75], [70, 80, 90, 100]])

In [57]:
array3 + array1

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [58]:
array1[0][2]

3

In [59]:
array1[0,2]

3

In [60]:
array1[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [61]:
array1[0:2,0]

array([1, 4])

In [64]:
array1 = np.array([[11, 2, 33], [4, 15, 6], [7, 8, 9]])

In [66]:
array1.min()

2

In [67]:
array1.max()

33

In [69]:
a3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [70]:
temp1 = a3.reshape(4, 3)

In [71]:
temp1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
temp1.shape

(4, 3)

In [73]:
temp2 = temp1.reshape(-1)

In [74]:
temp2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
temp3 = temp1.reshape(3, 4)

In [76]:
temp3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

pip install pandas

In [77]:
import pandas as pd

In [78]:
d = pd.Series([1, 2, 3, 4])

In [79]:
d

0    1
1    2
2    3
3    4
dtype: int64

In [80]:
d = pd.Series([1, 2, 3, 4], index=['a', 's', 'd', 'f'])

In [81]:
d

a    1
s    2
d    3
f    4
dtype: int64

In [82]:
d.index

Index(['a', 's', 'd', 'f'], dtype='object')

In [83]:
d.values

array([1, 2, 3, 4])

In [84]:
d[2]

/tmp/ipykernel_39450/464593666.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  d[2]


3

In [85]:
df = pd.DataFrame({'Count':[ 10, 20, 30], 'Toys': ['t1', 't2', 't3']})

In [86]:
df

Count Toys
0     10   t1
1     20   t2
2     30   t3

In [87]:
new_dict = {"Город": ["Москва", "Сочи", "Краснодар", "Тула", "Орёл", "Спб", "Тверь"],
		"Кол-во магазинов": [17, 2, 5, 3, 1, 10, 4],
		"Товар": ["Продукты", "Всё для дома", "Аптека", "Детский", "Стройматериалы", "Продукты", "Аптека"],
		"Доход": [100000, 20300, 75000, 17000, 5700, 75000, 5700]}

In [88]:
new_dict

{'Город': ['Москва', 'Сочи', 'Краснодар', 'Тула', 'Орёл', 'Спб', 'Тверь'],
 'Кол-во магазинов': [17, 2, 5, 3, 1, 10, 4],
 'Товар': ['Продукты',
  'Всё для дома',
  'Аптека',
  'Детский',
  'Стройматериалы',
  'Продукты',
  'Аптека'],
 'Доход': [100000, 20300, 75000, 17000, 5700, 75000, 5700]}

In [89]:
df = pd.DataFrame(new_dict)

In [90]:
df

Город  Кол-во магазинов           Товар   Доход
0     Москва                17        Продукты  100000
1       Сочи                 2    Всё для дома   20300
2  Краснодар                 5          Аптека   75000
3       Тула                 3         Детский   17000
4       Орёл                 1  Стройматериалы    5700
5        Спб                10        Продукты   75000
6      Тверь                 4          Аптека    5700

In [92]:
df['Товар']

0          Продукты
1      Всё для дома
2            Аптека
3           Детский
4    Стройматериалы
5          Продукты
6            Аптека
Name: Товар, dtype: object

In [93]:
df['Доход']

0    100000
1     20300
2     75000
3     17000
4      5700
5     75000
6      5700
Name: Доход, dtype: int64

In [96]:
df['Товар'][1:4]

1    Всё для дома
2          Аптека
3         Детский
Name: Товар, dtype: object

In [97]:
df[['Доход', 'Товар']]

Доход           Товар
0  100000        Продукты
1   20300    Всё для дома
2   75000          Аптека
3   17000         Детский
4    5700  Стройматериалы
5   75000        Продукты
6    5700          Аптека

In [98]:
df[['Товар', 'Доход']]

Товар   Доход
0        Продукты  100000
1    Всё для дома   20300
2          Аптека   75000
3         Детский   17000
4  Стройматериалы    5700
5        Продукты   75000
6          Аптека    5700

In [99]:
df[0:3]

Город  Кол-во магазинов         Товар   Доход
0     Москва                17      Продукты  100000
1       Сочи                 2  Всё для дома   20300
2  Краснодар                 5        Аптека   75000

In [100]:
df.iloc[0]

Город                 Москва
Кол-во магазинов          17
Товар               Продукты
Доход                 100000
Name: 0, dtype: object

In [101]:
df.iloc[1: 3]

Город  Кол-во магазинов         Товар  Доход
1       Сочи                 2  Всё для дома  20300
2  Краснодар                 5        Аптека  75000

In [102]:
df.iloc[1: 3, 1: 3]

Кол-во магазинов         Товар
1                 2  Всё для дома
2                 5        Аптека

In [103]:
df.head()

Город  Кол-во магазинов           Товар   Доход
0     Москва                17        Продукты  100000
1       Сочи                 2    Всё для дома   20300
2  Краснодар                 5          Аптека   75000
3       Тула                 3         Детский   17000
4       Орёл                 1  Стройматериалы    5700

In [104]:
df.head(3)

Город  Кол-во магазинов         Товар   Доход
0     Москва                17      Продукты  100000
1       Сочи                 2  Всё для дома   20300
2  Краснодар                 5        Аптека   75000

In [105]:
df.tail()

Город  Кол-во магазинов           Товар  Доход
2  Краснодар                 5          Аптека  75000
3       Тула                 3         Детский  17000
4       Орёл                 1  Стройматериалы   5700
5        Спб                10        Продукты  75000
6      Тверь                 4          Аптека   5700

In [106]:
df.tail(2)

Город  Кол-во магазинов     Товар  Доход
5    Спб                10  Продукты  75000
6  Тверь                 4    Аптека   5700

In [107]:
df.sample(2)

Город  Кол-во магазинов     Товар   Доход
6   Тверь                 4    Аптека    5700
0  Москва                17  Продукты  100000

In [108]:
df.sample(2)

Город  Кол-во магазинов         Товар  Доход
3  Тула                 3       Детский  17000
1  Сочи                 2  Всё для дома  20300

In [109]:
df.sample(2)

Город  Кол-во магазинов     Товар  Доход
5   Спб                10  Продукты  75000
3  Тула                 3   Детский  17000

In [110]:
df.shape

(7, 4)

In [111]:
df.columns

Index(['Город', 'Кол-во магазинов', 'Товар', 'Доход'], dtype='object')

In [112]:
df.values

array([['Москва', 17, 'Продукты', 100000],
       ['Сочи', 2, 'Всё для дома', 20300],
       ['Краснодар', 5, 'Аптека', 75000],
       ['Тула', 3, 'Детский', 17000],
       ['Орёл', 1, 'Стройматериалы', 5700],
       ['Спб', 10, 'Продукты', 75000],
       ['Тверь', 4, 'Аптека', 5700]], dtype=object)

In [113]:
df

Город  Кол-во магазинов           Товар   Доход
0     Москва                17        Продукты  100000
1       Сочи                 2    Всё для дома   20300
2  Краснодар                 5          Аптека   75000
3       Тула                 3         Детский   17000
4       Орёл                 1  Стройматериалы    5700
5        Спб                10        Продукты   75000
6      Тверь                 4          Аптека    5700

In [114]:
df.sort_values(by='Кол-во магазинов')

Город  Кол-во магазинов           Товар   Доход
4       Орёл                 1  Стройматериалы    5700
1       Сочи                 2    Всё для дома   20300
3       Тула                 3         Детский   17000
6      Тверь                 4          Аптека    5700
2  Краснодар                 5          Аптека   75000
5        Спб                10        Продукты   75000
0     Москва                17        Продукты  100000

In [115]:
df.sort_values(by='Доход')

Город  Кол-во магазинов           Товар   Доход
4       Орёл                 1  Стройматериалы    5700
6      Тверь                 4          Аптека    5700
3       Тула                 3         Детский   17000
1       Сочи                 2    Всё для дома   20300
2  Краснодар                 5          Аптека   75000
5        Спб                10        Продукты   75000
0     Москва                17        Продукты  100000

In [116]:
df.sort_values(by='Город')

Город  Кол-во магазинов           Товар   Доход
2  Краснодар                 5          Аптека   75000
0     Москва                17        Продукты  100000
4       Орёл                 1  Стройматериалы    5700
1       Сочи                 2    Всё для дома   20300
5        Спб                10        Продукты   75000
6      Тверь                 4          Аптека    5700
3       Тула                 3         Детский   17000

In [120]:
df.sort_values(by=['Доход', 'Товар'], ascending=[False, True])

Город  Кол-во магазинов           Товар   Доход
0     Москва                17        Продукты  100000
2  Краснодар                 5          Аптека   75000
5        Спб                10        Продукты   75000
1       Сочи                 2    Всё для дома   20300
3       Тула                 3         Детский   17000
6      Тверь                 4          Аптека    5700
4       Орёл                 1  Стройматериалы    5700

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Город             7 non-null      object
 1   Кол-во магазинов  7 non-null      int64 
 2   Товар             7 non-null      object
 3   Доход             7 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 356.0+ bytes


In [122]:
df.describe()

Кол-во магазинов          Доход
count          7.000000       7.000000
mean           6.000000   42671.428571
std            5.656854   39306.730309
min            1.000000    5700.000000
25%            2.500000   11350.000000
50%            4.000000   20300.000000
75%            7.500000   75000.000000
max           17.000000  100000.000000

In [123]:
df

Город  Кол-во магазинов           Товар   Доход
0     Москва                17        Продукты  100000
1       Сочи                 2    Всё для дома   20300
2  Краснодар                 5          Аптека   75000
3       Тула                 3         Детский   17000
4       Орёл                 1  Стройматериалы    5700
5        Спб                10        Продукты   75000
6      Тверь                 4          Аптека    5700

In [124]:
df['Доход']

0    100000
1     20300
2     75000
3     17000
4      5700
5     75000
6      5700
Name: Доход, dtype: int64

In [125]:
df['Доход'] > 10000

0     True
1     True
2     True
3     True
4    False
5     True
6    False
Name: Доход, dtype: bool

In [126]:
list_1 = df['Доход'] > 10000

In [127]:
df[list_1]

Город  Кол-во магазинов         Товар   Доход
0     Москва                17      Продукты  100000
1       Сочи                 2  Всё для дома   20300
2  Краснодар                 5        Аптека   75000
3       Тула                 3       Детский   17000
5        Спб                10      Продукты   75000

In [128]:
df[df['Доход'] > 20000]

Город  Кол-во магазинов         Товар   Доход
0     Москва                17      Продукты  100000
1       Сочи                 2  Всё для дома   20300
2  Краснодар                 5        Аптека   75000
5        Спб                10      Продукты   75000