## Семинар NumPy

pip install numpy

In [1]:
import numpy as np

In [3]:
array1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [4]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.random.random(5)

array([0.23026832, 0.1503466 , 0.34925894, 0.69241732, 0.61690614])

In [8]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [10]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
np.zeros([3,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
array1.ndim

2

In [15]:
array1.shape

(3, 3)

In [16]:
array2 = np.zeros([3,7])

In [17]:
array2.shape

(3, 7)

In [18]:
array1.size

9

In [19]:
array2.size

21

In [20]:
array1.dtype

dtype('int64')

In [21]:
array1.itemsize

8

In [22]:
array2.itemsize

8

In [23]:
data1 = np.array([1, 2])

In [24]:
data1

array([1, 2])

In [25]:
data2 = np.ones(2)

In [26]:
data2

array([1., 1.])

In [27]:
res = data1 + data2

In [28]:
res

array([2., 3.])

In [29]:
res = data1 - data2

In [30]:
res

array([0., 1.])

In [31]:
data1 * data2

array([1., 2.])

In [32]:
array1  * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [33]:
data1 * 4

array([4, 8])

In [34]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
data3 = ([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
data3

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
data3[0]

1

In [39]:
data3[2]

3

In [40]:
data3[1:5]

[2, 3, 4, 5]

In [41]:
data3[1:]

[2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
data3[1:8:2]

[2, 4, 6, 8]

In [43]:
data3.min()

AttributeError: 'list' object has no attribute 'min'

In [44]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
data3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
data3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
data3[0]

1

In [48]:
data3[1:5]

array([2, 3, 4, 5])

In [49]:
data3[1:8:2]

array([2, 4, 6, 8])

In [50]:
data3.min()

1

In [51]:
data3.max()

9

In [52]:
data3.sum()

45

In [53]:
data3.mean()

5.0

In [54]:
data3.prod()

362880

In [55]:
array1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [56]:
array3 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
])

In [57]:
array3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [58]:
array1 + array3

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [59]:
array1 - array3

array([[ -9, -18, -27],
       [-36, -45, -54],
       [-63, -72, -81]])

In [60]:
array3 - array1

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [61]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
array1[0, 2]

3

In [63]:
array1[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [64]:
array1[1:3, :2]

array([[4, 5],
       [7, 8]])

In [65]:
array1.min()

1

In [66]:
array1.max()

9

In [67]:
array1.sum()

45

In [68]:
array1.mean()

5.0

In [69]:
array1.shape

(3, 3)

In [73]:
data3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [74]:
data3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
data3.shape

(10,)

In [77]:
data4 = data3.reshape(5, 2)

In [78]:
data4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [82]:
data5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [83]:
data7 = data5.reshape(2, 3, 2)

In [84]:
data7

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [89]:
array5 = np.array([
    [17, 3, 30],
    [10, 5, 12],
    [7, 10, 9],
])

In [90]:
array5.max()

30

In [91]:
array5.max(axis=0)

array([17, 10, 30])

In [92]:
array5.max(axis=1)

array([30, 12, 10])

# PANDAS

pip install pandas

In [93]:
import pandas as pd

In [94]:
data = pd.Series([4, 5, 7, 8, 2, 1])

In [95]:
data

0    4
1    5
2    7
3    8
4    2
5    1
dtype: int64

In [96]:
data = pd.Series([4, 5, 7, 1], index=['a', 'b', 'c', 'd'])

In [97]:
data

a    4
b    5
c    7
d    1
dtype: int64

In [98]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [99]:
data.values

array([4, 5, 7, 1])

In [100]:
data[0]

/tmp/ipykernel_14978/1743741225.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[0]


4

In [101]:
data['b']

5

In [102]:
my_dict = {
'Count': [46, 37, 44, 42,  25],
'Toys': ['Toys1', 'Toys2', 'Toys3', 'Toys4', 'Toys5'],
'Name': ['Car', 'Book', 'Pen', 'Fruit', 'ball' ]
}


In [103]:
my_dict

{'Count': [46, 37, 44, 42, 25],
 'Toys': ['Toys1', 'Toys2', 'Toys3', 'Toys4', 'Toys5'],
 'Name': ['Car', 'Book', 'Pen', 'Fruit', 'ball']}

In [105]:
df = pd.DataFrame(my_dict)

In [106]:
df

Count   Toys   Name
0     46  Toys1    Car
1     37  Toys2   Book
2     44  Toys3    Pen
3     42  Toys4  Fruit
4     25  Toys5   ball

In [107]:
new_dict = {"Город": ["Москва", "Сочи", "Краснодар", "Тула", "Орёл", "Спб", "Тверь"],
		"Кол-во магазинов": [17, 2, 5, 3, 1, 10, 4],
		"Товар": ["Продукты", "Всё для дома", "Аптека", "Детский", "Стройматериалы", "Продукты", "Аптека"],
		"Доход": [100000, 20300, 75000, 17000, 5700, 75000, 5700]}

In [110]:
df1 = pd.DataFrame(new_dict)

In [111]:
df1

Город  Кол-во магазинов           Товар   Доход
0     Москва                17        Продукты  100000
1       Сочи                 2    Всё для дома   20300
2  Краснодар                 5          Аптека   75000
3       Тула                 3         Детский   17000
4       Орёл                 1  Стройматериалы    5700
5        Спб                10        Продукты   75000
6      Тверь                 4          Аптека    5700

In [112]:
type(df1)

pandas.core.frame.DataFrame

In [114]:
df1['Доход']

0    100000
1     20300
2     75000
3     17000
4      5700
5     75000
6      5700
Name: Доход, dtype: int64

In [115]:
df1['Город']

0       Москва
1         Сочи
2    Краснодар
3         Тула
4         Орёл
5          Спб
6        Тверь
Name: Город, dtype: object

In [116]:
df1['Город'][1:3]

1         Сочи
2    Краснодар
Name: Город, dtype: object

In [119]:
df1[['Доход', 'Товар', 'Город']]

Доход           Товар      Город
0  100000        Продукты     Москва
1   20300    Всё для дома       Сочи
2   75000          Аптека  Краснодар
3   17000         Детский       Тула
4    5700  Стройматериалы       Орёл
5   75000        Продукты        Спб
6    5700          Аптека      Тверь

In [120]:
df1[0:3]

Город  Кол-во магазинов         Товар   Доход
0     Москва                17      Продукты  100000
1       Сочи                 2  Всё для дома   20300
2  Краснодар                 5        Аптека   75000

In [122]:
df1.iloc[0]

Город                 Москва
Кол-во магазинов          17
Товар               Продукты
Доход                 100000
Name: 0, dtype: object

In [123]:
df1.iloc[1]

Город                       Сочи
Кол-во магазинов               2
Товар               Всё для дома
Доход                      20300
Name: 1, dtype: object

In [124]:
df1.iloc[1:3]

Город  Кол-во магазинов         Товар  Доход
1       Сочи                 2  Всё для дома  20300
2  Краснодар                 5        Аптека  75000

In [125]:
df1

Город  Кол-во магазинов           Товар   Доход
0     Москва                17        Продукты  100000
1       Сочи                 2    Всё для дома   20300
2  Краснодар                 5          Аптека   75000
3       Тула                 3         Детский   17000
4       Орёл                 1  Стройматериалы    5700
5        Спб                10        Продукты   75000
6      Тверь                 4          Аптека    5700

In [126]:
df1.iloc[1, 1]

2

In [127]:
df1.iloc[2, 2]

'Аптека'

In [128]:
df1.iloc[1:3, 2:]

Товар  Доход
1  Всё для дома  20300
2        Аптека  75000