In [4]:
# pip install numpy

import numpy as np
from numpy import doc

print(repr(np))

help(doc)

<module 'numpy' from '/Users/suren/MyFiles/OTUS/lessons/Python-Basic.2023.02/38.numpy/venv/lib/python3.11/site-packages/numpy/__init__.py'>
Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - constants
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    constants
    ufuncs

DATA
    __all__ = ['constants', 'ufuncs', '__doc__']

FILE
    /Users/suren/MyFiles/OTUS/lessons/Python-Basic.2023.02/38.numpy/venv/lib/python3.11/site-packages/numpy/doc/__init__.py




In [5]:
np.array

<function numpy.array>

In [6]:
a = np.array([1, 2, 3])
print(a)
print(repr(a))
print(type(a))

[1 2 3]
array([1, 2, 3])
<class 'numpy.ndarray'>


In [7]:
print("dim:", a.ndim)
print("shape", a.shape)

dim: 1
shape (3,)


In [8]:
a.dtype

dtype('int64')

In [9]:
a.itemsize

8

In [10]:
b = np.array([
    [4, 5, 6],
    [7, 8, 9],
])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [11]:
print("dim:", b.ndim)
print("shape", b.shape)
print("size:", b.size)

dim: 2
shape (2, 3)
size: 6


In [13]:
b.dtype

dtype('int64')

In [14]:
b.dtype.name

'int64'

In [15]:
print(b.dtype)
print(b.itemsize)

int64
8


In [16]:
b.dtype = np.int32
print(b.dtype)
print(b.itemsize)

int32
4


In [17]:
c = np.array([1, 2, 3, 4], dtype=np.int8)
c

array([1, 2, 3, 4], dtype=int8)

In [18]:
c.itemsize

1

In [19]:
np.array(range(1, 12))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.array(range(8))

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
np.array(range(15, 115, 5))

array([ 15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,
        80,  85,  90,  95, 100, 105, 110])

In [23]:
np.arange(15, 115, 5)

array([ 15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,
        80,  85,  90,  95, 100, 105, 110])

In [24]:
a = np.arange(15, 115, 5).reshape(4, 5)
a

array([[ 15,  20,  25,  30,  35],
       [ 40,  45,  50,  55,  60],
       [ 65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110]])

In [25]:
a.ndim

2

In [26]:
a.shape

(4, 5)

In [27]:
a = np.array([1, 2])
a

array([1, 2])

In [28]:
a.dtype

dtype('int64')

In [29]:
a.fill(3)
a

array([3, 3])

In [30]:
a = np.empty(2)
a

array([6.68130202e-125, 1.22920287e+300])

In [31]:
a.dtype

dtype('float64')

In [32]:
a.fill(1)
a

array([1., 1.])

In [33]:
a.dtype

dtype('float64')

In [34]:
a = np.arange(1, 5, 0.5)
a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [35]:
a.dtype

dtype('float64')

In [36]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [37]:
a = np.linspace(0, 6, 20)
print(a)

[0.         0.31578947 0.63157895 0.94736842 1.26315789 1.57894737
 1.89473684 2.21052632 2.52631579 2.84210526 3.15789474 3.47368421
 3.78947368 4.10526316 4.42105263 4.73684211 5.05263158 5.36842105
 5.68421053 6.        ]


In [38]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
SIZE = 10
SHAPE = (SIZE, )

np.zeros(SHAPE)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
SIZE_X = 3
SIZE_Y = 5
SHAPE = (SIZE_X, SIZE_Y)

a = np.zeros(SHAPE)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
a.dtype

dtype('float64')

In [44]:
a.size

15

In [45]:
a.shape

(3, 5)

In [47]:
a = np.zeros(SHAPE, dtype=np.int32)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [48]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
b = np.arange(20, 40, 2)
b

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [51]:
for a_i, b_i in zip(a, b):
    print(a_i + b_i)

21
24
27
30
33
36
39
42
45
48


In [52]:
a + b

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [53]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [54]:
b - a

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [55]:
a * b

array([ 20,  44,  72, 104, 140, 180, 224, 272, 324, 380])

In [56]:
SHAPE = 2, 3
a = np.arange(1, 7).reshape(SHAPE)
b = np.arange(9, 15).reshape(SHAPE)

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [57]:
print(a.shape)
print(b.shape)

(2, 3)
(2, 3)


In [58]:
a + b

array([[10, 12, 14],
       [16, 18, 20]])

In [59]:
a * b

array([[ 9, 20, 33],
       [48, 65, 84]])

In [60]:
b - a

array([[8, 8, 8],
       [8, 8, 8]])

In [61]:
a - b

array([[-8, -8, -8],
       [-8, -8, -8]])

In [62]:
b / a

array([[9.        , 5.        , 3.66666667],
       [3.        , 2.6       , 2.33333333]])

In [63]:
a / b

array([[0.11111111, 0.2       , 0.27272727],
       [0.33333333, 0.38461538, 0.42857143]])

In [64]:
# operands could not be broadcast together with shapes (2,) (3,) 
np.arange(2) + np.arange(3)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [65]:
a = np.arange(10)
b = np.arange(10, 20)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [66]:
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [67]:
a / b

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [68]:
b / a

/var/folders/r0/f247yh3j4djfkghshd5yf41m0000gn/T/ipykernel_47464/1491818542.py:1: RuntimeWarning: divide by zero encountered in divide
  b / a


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111])

In [70]:
np.diff

<function diff at 0x1131efa30>

In [71]:
np.diff(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [72]:
np.diff(np.array([1, 3, 2, 8, 4, 9]))

array([ 2, -1,  6, -4,  5])

In [85]:
a = np.geomspace(1, 128, num=8)
a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [86]:
a = a.reshape(2, 4)
a

array([[  1.,   2.,   4.,   8.],
       [ 16.,  32.,  64., 128.]])

In [87]:
a.ndim

2

In [88]:
a.shape

(2, 4)

In [89]:
np.diff(a)

array([[ 1.,  2.,  4.],
       [16., 32., 64.]])

In [92]:
a = np.geomspace(1, 550, num=12).reshape(3, 4)
a

array([[  1.        ,   1.77469563,   3.14954459,   5.58948304],
       [  9.91963114,  17.60432608,  31.24232064,  55.44561003],
       [ 98.39908203, 174.62842127, 309.91229678, 550.        ]])

In [93]:
np.diff(a)

array([[  0.77469563,   1.37484896,   2.43993845],
       [  7.68469494,  13.63799455,  24.20328939],
       [ 76.22933923, 135.28387552, 240.08770322]])

In [94]:
np.sum(a)

1258.6654112298233

In [95]:
sum([1, 2, 3])

6

In [97]:
a = np.linspace(1, 10, 4)
a

array([ 1.,  4.,  7., 10.])

In [98]:
np.sum(a)

22.0

In [99]:
a

array([ 1.,  4.,  7., 10.])

In [100]:
a * 3

array([ 3., 12., 21., 30.])

In [101]:
a

array([ 1.,  4.,  7., 10.])

In [106]:
a = np.geomspace(1, 128, num=8, dtype=np.float16).reshape(2, 4)
a

array([[  1.,   2.,   4.,   8.],
       [ 16.,  32.,  64., 128.]], dtype=float16)

In [107]:
np.sum(a)

255.0

In [108]:
a * 2

array([[  2.,   4.,   8.,  16.],
       [ 32.,  64., 128., 256.]], dtype=float16)

In [109]:
np.sum(a, axis=0)

array([ 17.,  34.,  68., 136.], dtype=float16)

In [111]:
a.shape

(2, 4)

In [112]:
a.shape[0]

2

In [113]:
a.shape[1]

4

In [114]:
np.sum(a, axis=1)

array([ 15., 240.], dtype=float16)

In [117]:
np.prod(a, dtype=np.float32)

268435460.0

In [118]:
np.prod(a, axis=0)

array([  16.,   64.,  256., 1024.], dtype=float16)

In [120]:
np.prod(a, axis=1, dtype=np.float64)

array([6.400000e+01, 4.194304e+06])

In [121]:
16 *  32 *  64 * 128

4194304

In [122]:
a

array([[  1.,   2.,   4.,   8.],
       [ 16.,  32.,  64., 128.]], dtype=float16)

In [123]:
a ** 2

array([[1.000e+00, 4.000e+00, 1.600e+01, 6.400e+01],
       [2.560e+02, 1.024e+03, 4.096e+03, 1.638e+04]], dtype=float16)

In [127]:
a = np.arange(10, 30).reshape(4, 5)
print(a.ndim)
print(a.shape)
a

2
(4, 5)


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [128]:
transposed_a = a.transpose()
print(transposed_a.ndim)
print(transposed_a.shape)
transposed_a

2
(5, 4)


array([[10, 15, 20, 25],
       [11, 16, 21, 26],
       [12, 17, 22, 27],
       [13, 18, 23, 28],
       [14, 19, 24, 29]])

In [129]:
a.T

array([[10, 15, 20, 25],
       [11, 16, 21, 26],
       [12, 17, 22, 27],
       [13, 18, 23, 28],
       [14, 19, 24, 29]])

In [130]:
np.linalg

<module 'numpy.linalg' from '/Users/suren/MyFiles/OTUS/lessons/Python-Basic.2023.02/38.numpy/venv/lib/python3.11/site-packages/numpy/linalg/__init__.py'>

In [131]:
a = np.arange(10, 30, 5).reshape(2, 2)
print(a)
np.linalg.det(a)

[[10 15]
 [20 25]]


-49.99999999999999

In [132]:
a = np.array([[1, 2], [3, 4]])
print(a)
np.linalg.det(a)

[[1 2]
 [3 4]]


-2.0000000000000004

In [133]:
0.1 + 0.2

0.30000000000000004

In [134]:
a = np.array([0.1])
b = np.array([0.2])
print(a)
print(b)
a + b

[0.1]
[0.2]


array([0.3])

In [135]:
a

array([0.1])

In [140]:
a = np.arange(10, 22).reshape(3, 4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [141]:
a > 13

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [142]:
result = a > 13
print(result.dtype)
print(result.ndim)
print(result.shape)
print(a.shape)

bool
2
(3, 4)
(3, 4)


In [143]:
result.dtype

dtype('bool')

In [144]:
a == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [146]:
b = np.arange(23, 11, -1).reshape(3, 4)
b

array([[23, 22, 21, 20],
       [19, 18, 17, 16],
       [15, 14, 13, 12]])

In [147]:
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [148]:
a > b

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [149]:
a - b

array([[-13, -11,  -9,  -7],
       [ -5,  -3,  -1,   1],
       [  3,   5,   7,   9]])

In [150]:
a / b

array([[0.43478261, 0.5       , 0.57142857, 0.65      ],
       [0.73684211, 0.83333333, 0.94117647, 1.0625    ],
       [1.2       , 1.35714286, 1.53846154, 1.75      ]])

In [151]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
a[0]

0

In [153]:
a[2]

2

In [154]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [155]:
a[0]

10

In [156]:
a[9]

19

In [157]:
a[:5]

array([10, 11, 12, 13, 14])

In [158]:
a[6:]

array([16, 17, 18, 19])

In [159]:
a[3:7]

array([13, 14, 15, 16])

In [160]:
a[2:7:3]

array([12, 15])

In [161]:
a[3:8:2]

array([13, 15, 17])

In [162]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [163]:
a[3:7:2]

array([13, 15])

In [164]:
a[2:7:3]

array([12, 15])

In [165]:
a[2:8:3]

array([12, 15])

In [166]:
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [167]:
numbers = list(range(1, 8))
print(numbers)

[1, 2, 3, 4, 5, 6, 7]


In [168]:
numbers[2:5]

[3, 4, 5]

In [169]:
numbers[2:5] = [9, 10, 11]
print(numbers)

[1, 2, 9, 10, 11, 6, 7]


In [170]:
numbers[2:5] = [-1, -2]
numbers

[1, 2, -1, -2, 6, 7]

In [171]:
numbers[2:5] = [4]

In [172]:
numbers

[1, 2, 4, 7]

In [173]:
numbers[2:3] = 1

TypeError: can only assign an iterable

In [174]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [175]:
a[3:5]

array([13, 14])

In [176]:
a[3:5] = [3, 4]

In [177]:
a

array([10, 11, 12,  3,  4, 15, 16, 17, 18, 19])

In [178]:
a.dtype

dtype('int64')

In [179]:
a[3:6] = 7
a

array([10, 11, 12,  7,  7,  7, 16, 17, 18, 19])

In [180]:
a[:5:3]

array([10,  7])

In [181]:
a[:5:3] = 4
a

array([ 4, 11, 12,  4,  7,  7, 16, 17, 18, 19])

In [190]:
def func(x, y):
    return 10 * x + y 

SHAPE = (4, 5)
a = np.fromfunction(func, SHAPE, dtype=np.int64)
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [191]:
a.dtype

dtype('int64')

In [192]:
a.dtype = int

In [193]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [194]:
a.dtype

dtype('int64')

In [195]:
a[0]

array([0, 1, 2, 3, 4])

In [196]:
a[-1]

array([30, 31, 32, 33, 34])

In [197]:
a[2]

array([20, 21, 22, 23, 24])

In [198]:
a[2][3]

23

In [199]:
a[2, 3]

23

In [200]:
a[3, 2]

32

In [201]:
a[:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [202]:
a[:, 1]

array([ 1, 11, 21, 31])

In [203]:
a[:, 1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32]])

In [204]:
a[2:, 1:3]

array([[21, 22],
       [31, 32]])

In [206]:
a[2:, 3:1:-1]

array([[23, 22],
       [33, 32]])

In [207]:
a[:2:-1, 3:1:-1]

array([[33, 32]])

In [212]:
a[:1:-1, 3:1:-1]

array([[33, 32],
       [23, 22]])

In [213]:
a[::-1]

array([[30, 31, 32, 33, 34],
       [20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [214]:
a[::-1, ::-1]

array([[34, 33, 32, 31, 30],
       [24, 23, 22, 21, 20],
       [14, 13, 12, 11, 10],
       [ 4,  3,  2,  1,  0]])

In [215]:
SHAPE_3D = (2, 4, 6)
a = np.arange(48).reshape(SHAPE_3D)
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [216]:
print(a.ndim)
print(a.shape)
print(a.size)

3
(2, 4, 6)
48


In [217]:
a[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [218]:
a[:, 2]

array([[12, 13, 14, 15, 16, 17],
       [36, 37, 38, 39, 40, 41]])

In [219]:
a[:, :, 5]

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

In [220]:
a[..., 5]

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

In [221]:
...

Ellipsis

In [222]:
SHAPE_5D = tuple(range(2, 7))
print(SHAPE_5D)

(2, 3, 4, 5, 6)


In [226]:
a = np.empty(SHAPE_5D, dtype=np.int16)
a

array([[[[[     0,      0,      0,      0,    204,      0],
          [     1,      0,   1536,   1428,      1,      0],
          [-15777,   4608,      1,      0, -16031,   5395],
          [     1,      0,      1,      0,      0,      0],
          [    -1,     -1,     -1,     -1,     -1,     -1]],

         [[    -1,     -1,   -464,   5379,      1,      0],
          [     0,      0,     -1,     -1, -11412,   4608],
          [     1,      0, -16031,   5395,      1,      0],
          [     1,      0,      9,      0,      0,      0],
          [     0,      0,      1,      0,      0,      0]],

         [[  -464,   5379,      1,      0,     28,      0],
          [    -1,     -1, -11396,   4608,      1,      0],
          [-16031,   5395,      1,      0,      1,      0],
          [    11,      0,     56,      0,      0,      0],
          [     0,      0,      0,      0,     10,      0]],

         [[     0,      0,     28,      0,     -1,     -1],
          [-11388,   4608,      1,

In [227]:
print(a.ndim)
print(a.shape)
print(a.size)

5
(2, 3, 4, 5, 6)
720


In [229]:
d = a[1, :, :, :, 3]
print(d.ndim)
print(d.shape)
print(d.size)
d

3
(3, 4, 5)
60


array([[[   0, 5430,    0, 5435,    0],
        [1274,    0,    0,    0, 5430],
        [   0,    0,    0, 1274,    0],
        [   0,    0, 5435,    0,    0]],

       [[   0, 5436,    0, 1342,    0],
        [1342,    0, 5436,    0, 1342],
        [   0, 5435,    0, 1342,    0],
        [5436,    0, 1342,    0, 1342]],

       [[   0, 5436,    0, 1342,    0],
        [5438,    0, 1342,    0, 5436],
        [   0, 1342,    0, 5436,    0],
        [5396,    0, 5398,    0, 5396]]], dtype=int16)

In [232]:
b = a[1, ..., 3]
b

array([[[   0, 5430,    0, 5435,    0],
        [1274,    0,    0,    0, 5430],
        [   0,    0,    0, 1274,    0],
        [   0,    0, 5435,    0,    0]],

       [[   0, 5436,    0, 1342,    0],
        [1342,    0, 5436,    0, 1342],
        [   0, 5435,    0, 1342,    0],
        [5436,    0, 1342,    0, 1342]],

       [[   0, 5436,    0, 1342,    0],
        [5438,    0, 1342,    0, 5436],
        [   0, 1342,    0, 5436,    0],
        [5396,    0, 5398,    0, 5396]]], dtype=int16)

In [233]:
d == b

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [238]:
k = a[1, ..., 3:5]
k

array([[[[     0,  11955],
         [  5430,      1],
         [     0,      0],
         [  5435,      1],
         [     0,      4]],

        [[  1274,      1],
         [     0,      1],
         [     0,      0],
         [     0,  11955],
         [  5430,      1]],

        [[     0,  11959],
         [     0,      0],
         [     0, -17096],
         [  1274,      1],
         [     0,      1]],

        [[     0,      0],
         [     0, -17096],
         [  5435,      1],
         [     0,  28640],
         [     0,      3]]],


       [[[     0, -17096],
         [  5436,      1],
         [     0,  15888],
         [  1342,      1],
         [     0,  28864]],

        [[  1342,      1],
         [     0, -17096],
         [  5436,      1],
         [     0,  16080],
         [  1342,      1]],

        [[     0, -17096],
         [  5435,      1],
         [     0,  29200],
         [  1342,      1],
         [     0, -17096]],

        [[  5436,      1],
         [  

In [244]:
c = a[1, ..., 3:-2]
c

array([[[[   0],
         [5430],
         [   0],
         [5435],
         [   0]],

        [[1274],
         [   0],
         [   0],
         [   0],
         [5430]],

        [[   0],
         [   0],
         [   0],
         [1274],
         [   0]],

        [[   0],
         [   0],
         [5435],
         [   0],
         [   0]]],


       [[[   0],
         [5436],
         [   0],
         [1342],
         [   0]],

        [[1342],
         [   0],
         [5436],
         [   0],
         [1342]],

        [[   0],
         [5435],
         [   0],
         [1342],
         [   0]],

        [[5436],
         [   0],
         [1342],
         [   0],
         [1342]]],


       [[[   0],
         [5436],
         [   0],
         [1342],
         [   0]],

        [[5438],
         [   0],
         [1342],
         [   0],
         [5436]],

        [[   0],
         [1342],
         [   0],
         [5436],
         [   0]],

        [[5396],
         [   0],
     

In [245]:
print(c.ndim)
print(c.shape)
print(c.size)

4
(3, 4, 5, 1)
60


In [246]:
print(k.ndim)
print(k.shape)
print(k.size)

4
(3, 4, 5, 2)
120
