pip install numpy

In [2]:
import numpy as np

In [4]:
array1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [6]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array2 = np.ones(3)

In [8]:
array2

array([1., 1., 1.])

In [9]:
array2 = np.zeros(4)

In [10]:
array2

array([0., 0., 0., 0.])

In [12]:
array3 = np.random.random(5)

In [13]:
array3

array([0.95646826, 0.86363775, 0.0634379 , 0.98095066, 0.09444944])

In [16]:
array4 = np.arange(10, 31, 5)

In [17]:
array4

array([10, 15, 20, 25, 30])

In [28]:
array5 = np.linspace(0, 2, 9)

In [29]:
array5

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
array6 = np.zeros([3, 4])

In [31]:
array6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
array4.ndim

1

In [33]:
array6.ndim

2

In [34]:
array4.shape

(5,)

In [35]:
array6.shape

(3, 4)

shape - возвращает кортеж

In [36]:
array6.size

12

size - кол-во элементов массива. Равно произведению длины осей (значений кортежа shape)

In [37]:
array6.dtype

dtype('float64')

In [38]:
array4.dtype

dtype('int64')

dtype - возвращает тип элементов массива

In [39]:
a1 = np.array([1, 2, 3])

In [40]:
a1

array([1, 2, 3])

In [41]:
a2 = np.array([10, 20, 30])

In [42]:
a2

array([10, 20, 30])

In [43]:
a1 + a2

array([11, 22, 33])

In [44]:
a1 - a2

array([ -9, -18, -27])

In [45]:
a1 * 5

array([ 5, 10, 15])

In [46]:
a2 / 2

array([ 5., 10., 15.])

In [48]:
a2[0] + 7

np.int64(17)

In [50]:
array4[1:4]

array([15, 20, 25])

In [51]:
array4[1:]

array([15, 20, 25, 30])

In [52]:
array4[:3]

array([10, 15, 20])

In [53]:
array4[1::2]

array([15, 25])

In [54]:
a3 = np.array([19, 1, 2, 3, 10, 12, 3, 7, 100, 7, 17])

In [56]:
print(a3.min())

1


In [57]:
a3.min()

np.int64(1)

In [58]:
a3.max()

np.int64(100)

In [59]:
a3.mean()

np.float64(16.454545454545453)

In [60]:
a3.prod()

np.int64(3418632000)

In [61]:
ar1 = np.array([
    [11, 2, 34, 0],
    [14, 5, 76, 10],
    [71, 18, 9, 21]
])

In [62]:
ar2 = np.array([
    [1, 12, 42, 10],
    [14, 5, 76, 15],
    [17, 12, 91, 31]
])

In [63]:
ar1 + a1

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [64]:
ar1 + ar2

array([[ 12,  14,  76,  10],
       [ 28,  10, 152,  25],
       [ 88,  30, 100,  52]])

In [65]:
ar2 - ar1

array([[-10,  10,   8,  10],
       [  0,   0,   0,   5],
       [-54,  -6,  82,  10]])

In [66]:
ar1 * 10

array([[110,  20, 340,   0],
       [140,  50, 760, 100],
       [710, 180,  90, 210]])

In [67]:
ar2 / 2

array([[ 0.5,  6. , 21. ,  5. ],
       [ 7. ,  2.5, 38. ,  7.5],
       [ 8.5,  6. , 45.5, 15.5]])

In [68]:
ar1

array([[11,  2, 34,  0],
       [14,  5, 76, 10],
       [71, 18,  9, 21]])

In [69]:
ar1[1][0]

np.int64(14)

In [70]:
ar1[1, 0]

np.int64(14)

In [72]:
ar1[1:3, 2:]

array([[76, 10],
       [ 9, 21]])

In [73]:
ar1.min()

np.int64(0)

In [74]:
ar1.max()

np.int64(76)

In [75]:
ar1

array([[11,  2, 34,  0],
       [14,  5, 76, 10],
       [71, 18,  9, 21]])

In [76]:
ar3 = np.array([11, 2, 34, 0, 14, 5, 76, 10, 71, 18, 9, 21])

In [77]:
ar3

array([11,  2, 34,  0, 14,  5, 76, 10, 71, 18,  9, 21])

In [78]:
ar1

array([[11,  2, 34,  0],
       [14,  5, 76, 10],
       [71, 18,  9, 21]])

In [80]:
ar1[1:3, :2]

array([[14,  5],
       [71, 18]])

In [81]:
ar3

array([11,  2, 34,  0, 14,  5, 76, 10, 71, 18,  9, 21])

In [83]:
ar3.shape

(12,)

In [85]:
ar4 = ar3.reshape(4, 3)

In [86]:
ar4

array([[11,  2, 34],
       [ 0, 14,  5],
       [76, 10, 71],
       [18,  9, 21]])

In [87]:
ar4.shape

(4, 3)

pip install pandas

In [88]:
import pandas as pd

In [89]:
a = pd.Series([4, 3, 2, 1])

In [90]:
a

0    4
1    3
2    2
3    1
dtype: int64

In [91]:
a1 = pd.Series([4, 3, 2, 1], index=['a', 'b', 'c', 'd'])

In [92]:
a1

a    4
b    3
c    2
d    1
dtype: int64

In [93]:
a1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [94]:
a1.values

array([4, 3, 2, 1])

In [95]:
a1[2]

/tmp/ipykernel_24506/3065876008.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  a1[2]


np.int64(2)

In [96]:
a1["b"]

np.int64(3)

In [98]:
df = pd.DataFrame(new_dict)

In [99]:
df

Город  Кол-во магазинов           Товар   Доход
0     Москва                17        Продукты  100000
1       Сочи                 2    Всё для дома   20300
2  Краснодар                 5          Аптека   75000
3       Тула                 3         Детский   17000
4       Орёл                 1  Стройматериалы    5700
5        Спб                10        Продукты   75000
6      Тверь                 4          Аптека    5700

In [100]:
new_dict1 = {"Город": ["Москва", "Сочи", "Краснодар", "Тула", "Орёл", "Спб", "Тверь", 'Адлер'],
		"Кол-во магазинов": [17, 2, 5, 3, 1, 10 ],
		"Товар": ["Продукты", "Всё для дома", "Аптека", "Детский", "Стройматериалы", "Продукты", "Аптека"],
		"Доход": [100000, 20300, 75000, 17000, 5700, 75000, 5700]}

In [101]:
df = pd.DataFrame(new_dict1)

ValueError: All arrays must be of the same length

In [102]:
df

Город  Кол-во магазинов           Товар   Доход
0     Москва                17        Продукты  100000
1       Сочи                 2    Всё для дома   20300
2  Краснодар                 5          Аптека   75000
3       Тула                 3         Детский   17000
4       Орёл                 1  Стройматериалы    5700
5        Спб                10        Продукты   75000
6      Тверь                 4          Аптека    5700

In [104]:
df['Город']

0       Москва
1         Сочи
2    Краснодар
3         Тула
4         Орёл
5          Спб
6        Тверь
Name: Город, dtype: object

In [105]:
df['Доход']

0    100000
1     20300
2     75000
3     17000
4      5700
5     75000
6      5700
Name: Доход, dtype: int64

In [107]:
df['Город'][1:4]

1         Сочи
2    Краснодар
3         Тула
Name: Город, dtype: object

In [109]:
df[['Доход', 'Город']]

Доход      Город
0  100000     Москва
1   20300       Сочи
2   75000  Краснодар
3   17000       Тула
4    5700       Орёл
5   75000        Спб
6    5700      Тверь

In [110]:
df[['Город', 'Доход']]

Город   Доход
0     Москва  100000
1       Сочи   20300
2  Краснодар   75000
3       Тула   17000
4       Орёл    5700
5        Спб   75000
6      Тверь    5700

In [111]:
df[0:3]

Город  Кол-во магазинов         Товар   Доход
0     Москва                17      Продукты  100000
1       Сочи                 2  Всё для дома   20300
2  Краснодар                 5        Аптека   75000

In [112]:
df.iloc[2]

Город               Краснодар
Кол-во магазинов            5
Товар                  Аптека
Доход                   75000
Name: 2, dtype: object

In [113]:
df.iloc[1]

Город                       Сочи
Кол-во магазинов               2
Товар               Всё для дома
Доход                      20300
Name: 1, dtype: object

In [114]:
df.iloc[1:3]

Город  Кол-во магазинов         Товар  Доход
1       Сочи                 2  Всё для дома  20300
2  Краснодар                 5        Аптека  75000

In [115]:
df.iloc[1, 3]

np.int64(20300)

In [116]:
df.iloc[1:3, 1:3]

Кол-во магазинов         Товар
1                 2  Всё для дома
2                 5        Аптека