In [5]:
import numpy as np
from numpy import doc

help(doc)
# help(doc.constants)

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - constants
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    constants
    ufuncs

DATA
    __all__ = ['constants', 'ufuncs', '__doc__']

FILE
    /Users/suren/MyFiles/OTUS/lessons/Python-Basic.2022-02/34.numpy/venv/lib/python3.10/site-packages/numpy/doc/__init__.py




In [6]:
np.array

<function numpy.array>

In [7]:
a = np.array([1, 2, 3])
print(a)
print(repr(a))
print(type(a))

[1 2 3]
array([1, 2, 3])
<class 'numpy.ndarray'>


In [8]:
print(a.ndim)
print(a.shape)

1
(3,)


In [9]:
a.dtype

dtype('int64')

In [10]:
a.itemsize

8

In [11]:
b = np.array([
    [4, 5, 6],
    [7, 8, 9],
])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [13]:
print(b.ndim)
print(b.shape)
print(b.size)

2
(2, 3)
6


In [14]:
print(b.dtype)

int64


In [15]:
print(b.dtype.name)

int64


In [16]:
print(repr(b.dtype))

dtype('int64')


In [17]:
np.int32

numpy.int32

In [18]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [20]:
print(b.dtype)
print(b.itemsize)
b.dtype = np.int32

print(b.dtype)
print(b.itemsize)

int64
8
int32
4


In [21]:
c = np.array([1, 2], dtype=np.int32)

print(c)
print(c.dtype)

[1 2]
int32


In [22]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
a = np.arange(15)
print(a)
print(a.shape)
a = a.reshape(3, 5)
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


In [26]:
b = np.arange(15, 115, 5).reshape(4, 5)
print(b)

[[ 15  20  25  30  35]
 [ 40  45  50  55  60]
 [ 65  70  75  80  85]
 [ 90  95 100 105 110]]


In [28]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(4, 5)
20
int64
8


In [29]:
a = np.arange(1, 5, 0.5)
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [30]:
print(a.size)

8


In [31]:
a = np.arange(0, 2, 0.3)
print(a)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [32]:
a = np.linspace(0, 6, 20)
print(a)

[0.         0.31578947 0.63157895 0.94736842 1.26315789 1.57894737
 1.89473684 2.21052632 2.52631579 2.84210526 3.15789474 3.47368421
 3.78947368 4.10526316 4.42105263 4.73684211 5.05263158 5.36842105
 5.68421053 6.        ]


In [34]:
print(np.linspace(1, 10, 3))

[ 1.   5.5 10. ]


In [36]:
a = np.arange(10)
b = np.arange(10, 20)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [38]:
SIZE = 10
SHAPE = (SIZE, )

res = np.zeros(SHAPE)
print(res)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [40]:
SIZE_X = 3
SIZE_Y = 5
SHAPE = (SIZE_X, SIZE_Y)

res = np.zeros(SHAPE)
print(res)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
res.dtype

dtype('float64')

In [42]:
a.dtype

dtype('int64')

In [43]:
SIZE_X = 3
SIZE_Y = 5
SHAPE = (SIZE_X, SIZE_Y)

res = np.zeros(SHAPE, dtype=a.dtype)
print(res)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [44]:
res.dtype

dtype('int64')

In [45]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# for i_a, i_b in zip(a, b):
#     ...

In [47]:
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [48]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [49]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [50]:
SHAPE = 2, 3
a = np.arange(1, 7).reshape(SHAPE)
b = np.arange(9, 15).reshape(SHAPE)

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [51]:
a + b

array([[10, 12, 14],
       [16, 18, 20]])

In [52]:
a * b

array([[ 9, 20, 33],
       [48, 65, 84]])

In [53]:
a - b

array([[-8, -8, -8],
       [-8, -8, -8]])

In [54]:
b - a

array([[8, 8, 8],
       [8, 8, 8]])

In [55]:
b / a

array([[9.        , 5.        , 3.66666667],
       [3.        , 2.6       , 2.33333333]])

In [56]:
a = np.arange(7)
b = np.arange(9)

# operands could not be broadcast together with shapes (7,) (9,) 
a + b

ValueError: operands could not be broadcast together with shapes (7,) (9,) 

In [57]:
a = np.arange(10)
b = np.arange(10, 20)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [58]:
a / b

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [59]:
b / a

/var/folders/r0/f247yh3j4djfkghshd5yf41m0000gn/T/ipykernel_5230/1491818542.py:1: RuntimeWarning: divide by zero encountered in divide
  b / a


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111])

In [60]:
np.diff

<function numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)>

In [61]:
np.diff(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [63]:
np.diff(np.array([1, 3, 2, 5, 7]))

array([ 2, -1,  3,  2])

In [64]:
a = np.arange(10, 50, 5).reshape(2, 4)
print(a)
np.diff(a)

[[10 15 20 25]
 [30 35 40 45]]


array([[5, 5, 5],
       [5, 5, 5]])

In [65]:
a * 3

array([[ 30,  45,  60,  75],
       [ 90, 105, 120, 135]])

In [66]:
np.sum(a)

220

In [67]:
np.sum(a * 3)

660

In [68]:
a.ndim

2

In [69]:
a.shape

(2, 4)

In [71]:
np.sum(a, axis=0)

array([40, 50, 60, 70])

In [72]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [73]:
np.sum(a, axis=1)

array([ 70, 150])

In [74]:
np.prod(a)

141750000000

In [75]:
np.prod(a, axis=0)

array([ 300,  525,  800, 1125])

In [76]:
np.prod(a, axis=1)

array([  75000, 1890000])

In [77]:
a ** 2

array([[ 100,  225,  400,  625],
       [ 900, 1225, 1600, 2025]])

In [78]:
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [79]:
a.transpose()

array([[10, 30],
       [15, 35],
       [20, 40],
       [25, 45]])

In [80]:
a = np.arange(10, 30).reshape(4, 5)
print(a)
print(a.transpose())

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[10 15 20 25]
 [11 16 21 26]
 [12 17 22 27]
 [13 18 23 28]
 [14 19 24 29]]


In [81]:
a = np.arange(10, 30, 5).reshape(2, 2)
print(a)

[[10 15]
 [20 25]]


In [82]:
np.linalg.det(a)

-49.99999999999999

In [83]:
a = np.arange(10, 19).reshape(3, 3)
print(a)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [84]:
np.linalg.det(a)

0.0

In [85]:
a * 3

array([[30, 33, 36],
       [39, 42, 45],
       [48, 51, 54]])

In [86]:
a * a

array([[100, 121, 144],
       [169, 196, 225],
       [256, 289, 324]])

In [87]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [88]:
a > 13

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [89]:
(a > 13).dtype

dtype('bool')

In [90]:
a == a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [91]:
a == 10

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [92]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [94]:
b = np.arange(20, 11, -1).reshape(3, 3)
print(b)

[[20 19 18]
 [17 16 15]
 [14 13 12]]


In [95]:
a > b

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [96]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [97]:
a == b

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [98]:
a / b

array([[0.5       , 0.57894737, 0.66666667],
       [0.76470588, 0.875     , 1.        ],
       [1.14285714, 1.30769231, 1.5       ]])

In [99]:
a = np.arange(10)

In [100]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
a[0]

0

In [102]:
a[5]

5

In [103]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [104]:
a[3]

27

In [105]:
a[:5]

array([ 0,  1,  8, 27, 64])

In [106]:
a[7:]

array([343, 512, 729])

In [107]:
a[3:7:2]

array([ 27, 125])

In [108]:
a[1:7:2]

array([  1,  27, 125])

In [109]:
for i in a:
    print(i)
    print(type(i))

0
<class 'numpy.int64'>
1
<class 'numpy.int64'>
8
<class 'numpy.int64'>
27
<class 'numpy.int64'>
64
<class 'numpy.int64'>
125
<class 'numpy.int64'>
216
<class 'numpy.int64'>
343
<class 'numpy.int64'>
512
<class 'numpy.int64'>
729
<class 'numpy.int64'>


In [110]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [111]:
list1 = [1, 2, 3, 4, 5, 6, 7]
print(list1)
list1[2:5] = [9, 8]
print(list1)

[1, 2, 3, 4, 5, 6, 7]
[1, 2, 9, 8, 6, 7]


In [112]:
list1[2:5] = 1

TypeError: can only assign an iterable

In [113]:
a[:9]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512])

In [114]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [115]:
a[:9:3]

array([  0,  27, 216])

In [116]:
a[:9:3] = 777
a

array([777,   1,   8, 777,  64, 125, 777, 343, 512, 729])

In [117]:
def f(x, y):
    print("x:", x)
    print("y:", y)
    return 10 * x + y

In [118]:
f(5, 7)

x: 5
y: 7


57

In [119]:
SHAPE = (4, 5)
a = np.fromfunction(f, SHAPE)
print(a)

x: [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]
y: [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[ 0.  1.  2.  3.  4.]
 [10. 11. 12. 13. 14.]
 [20. 21. 22. 23. 24.]
 [30. 31. 32. 33. 34.]]


In [120]:
a = np.fromfunction(f, SHAPE, dtype=np.int8)
print(a)

x: [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
y: [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [121]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]], dtype=int8)

In [122]:
a[1]

array([10, 11, 12, 13, 14], dtype=int8)

In [123]:
a[3]

array([30, 31, 32, 33, 34], dtype=int8)

In [124]:
a[2][3]

23

In [125]:
a[2, 3]

23

In [126]:
a[3, 2]

32

In [127]:
a[0, 0]

0

In [128]:
a[:, 3]

array([ 3, 13, 23, 33], dtype=int8)

In [129]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]], dtype=int8)

In [130]:
a[:, 2:3]

array([[ 2],
       [12],
       [22],
       [32]], dtype=int8)

In [131]:
a[:, 1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32]], dtype=int8)

In [132]:
a[1:, 1:3]

array([[11, 12],
       [21, 22],
       [31, 32]], dtype=int8)

In [133]:
a[-1]

array([30, 31, 32, 33, 34], dtype=int8)

In [134]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]], dtype=int8)

In [135]:
a[::-1]

array([[30, 31, 32, 33, 34],
       [20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]], dtype=int8)

In [136]:
a[::-1, ::-1]

array([[34, 33, 32, 31, 30],
       [24, 23, 22, 21, 20],
       [14, 13, 12, 11, 10],
       [ 4,  3,  2,  1,  0]], dtype=int8)

In [137]:
np.empty(20)

array([ 0.,  1.,  2.,  3.,  4., 10., 11., 12., 13., 14., 20., 21., 22.,
       23., 24., 30., 31., 32., 33., 34.])

In [138]:
np.empty(20)

array([ 0.,  1.,  2.,  3.,  4., 10., 11., 12., 13., 14., 20., 21., 22.,
       23., 24., 30., 31., 32., 33., 34.])

In [139]:
np.empty(10)

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323,
       3.0e-323, 3.5e-323, 4.0e-323, 4.4e-323])

In [140]:
a.shape

(4, 5)

In [142]:
b = np.empty(4, dtype=a.dtype)
print(b)
b.fill(3)
print(b)

[1 1 1 1]
[3 3 3 3]


In [143]:
a[b]

array([[30, 31, 32, 33, 34],
       [30, 31, 32, 33, 34],
       [30, 31, 32, 33, 34],
       [30, 31, 32, 33, 34]], dtype=int8)

In [144]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]], dtype=int8)

In [145]:
b

array([3, 3, 3, 3], dtype=int8)

In [146]:
c = np.empty(3, dtype=np.int8)
print(c)

[1 1 1]


In [147]:
a[c]

array([[10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14]], dtype=int8)

In [148]:
c = np.array([3, 1, 2], dtype=np.int8)
print(c)

[3 1 2]


In [149]:
a[c]

array([[30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]], dtype=int8)

In [150]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]], dtype=int8)

In [152]:
SHAPE_3D = (2, 4, 6)
a = np.arange(48).reshape(SHAPE_3D)
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [153]:
print(a.ndim)
print(a.size)
print(a.shape)

3
48
(2, 4, 6)


In [154]:
a[:, :, 5]

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

In [155]:
a[..., 5]

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

In [156]:
SHAPE_5D = tuple(range(2, 7))
print(SHAPE_5D)

(2, 3, 4, 5, 6)


In [157]:
a = np.empty(SHAPE_5D, dtype=np.int16)
print(a)

[[[[[     0      0      0      0     39      0]
    [     0      0      0      0      0      0]
    [ 18471   1046      1      0      0      0]
    [     0      0      0      0      0      0]
    [    -1     -1     -1     -1      0      0]]

   [[     0      0      1      0   5119   8191]
    [     0      0      0      0      9      0]
    [     0      0 -10200   1816      1      0]
    [ 14700   2689      1      0     -1     -1]
    [    -1     -1      0      0      0      0]]

   [[    -1     -1     -1     -1      0      0]
    [     0      0      1      0      1      0]
    [    72      0      0      0     11      0]
    [     0      0 -10200   1816      1      0]
    [ 14716   2689      1      0      1      0]]

   [[     0      0     28      0      0      0]
    [    -1     -1     -1     -1      0      0]
    [     0      0      1      0      1      0]
    [   144      0      0      0     11      0]
    [     0      0 -10200   1816      1      0]]]


  [[[ 14724   2689      1     

In [158]:
print(a.ndim)
print(a.size)
print(a.shape)

5
720
(2, 3, 4, 5, 6)


In [159]:
a[1, ..., 5]

array([[[    0,     0,  2689,    -1,    -1],
        [    0,     0,     0,  2689,     0],
        [    0,     0,  1807,     0,  1815],
        [    0,     0,     0,  1815,     0]],

       [[    0,     0,     0,     0,  1815],
        [    0,     0,     0, 19044,     0],
        [ 1813,     0,     0,     0, 19044],
        [   -1,     0,     0,  1813,     0]],

       [[ 1004,     0,     0,     0,  1004],
        [    0,  1004,     0,  1005,     0],
        [ 1004,     0,  1004,     0,  1004],
        [    0,  1004,     0,  1004,     0]]], dtype=int16)

In [160]:
(a[1, ..., 5]).shape

(3, 4, 5)

In [161]:
a = np.arange(a.size).reshape(a.shape)
print(a)

[[[[[  0   1   2   3   4   5]
    [  6   7   8   9  10  11]
    [ 12  13  14  15  16  17]
    [ 18  19  20  21  22  23]
    [ 24  25  26  27  28  29]]

   [[ 30  31  32  33  34  35]
    [ 36  37  38  39  40  41]
    [ 42  43  44  45  46  47]
    [ 48  49  50  51  52  53]
    [ 54  55  56  57  58  59]]

   [[ 60  61  62  63  64  65]
    [ 66  67  68  69  70  71]
    [ 72  73  74  75  76  77]
    [ 78  79  80  81  82  83]
    [ 84  85  86  87  88  89]]

   [[ 90  91  92  93  94  95]
    [ 96  97  98  99 100 101]
    [102 103 104 105 106 107]
    [108 109 110 111 112 113]
    [114 115 116 117 118 119]]]


  [[[120 121 122 123 124 125]
    [126 127 128 129 130 131]
    [132 133 134 135 136 137]
    [138 139 140 141 142 143]
    [144 145 146 147 148 149]]

   [[150 151 152 153 154 155]
    [156 157 158 159 160 161]
    [162 163 164 165 166 167]
    [168 169 170 171 172 173]
    [174 175 176 177 178 179]]

   [[180 181 182 183 184 185]
    [186 187 188 189 190 191]
    [192 193 194 195 196 1

In [163]:
print(a[0, ..., 3])

[[[  3   9  15  21  27]
  [ 33  39  45  51  57]
  [ 63  69  75  81  87]
  [ 93  99 105 111 117]]

 [[123 129 135 141 147]
  [153 159 165 171 177]
  [183 189 195 201 207]
  [213 219 225 231 237]]

 [[243 249 255 261 267]
  [273 279 285 291 297]
  [303 309 315 321 327]
  [333 339 345 351 357]]]


In [164]:
print(a[0, ..., 1:3])

[[[[  1   2]
   [  7   8]
   [ 13  14]
   [ 19  20]
   [ 25  26]]

  [[ 31  32]
   [ 37  38]
   [ 43  44]
   [ 49  50]
   [ 55  56]]

  [[ 61  62]
   [ 67  68]
   [ 73  74]
   [ 79  80]
   [ 85  86]]

  [[ 91  92]
   [ 97  98]
   [103 104]
   [109 110]
   [115 116]]]


 [[[121 122]
   [127 128]
   [133 134]
   [139 140]
   [145 146]]

  [[151 152]
   [157 158]
   [163 164]
   [169 170]
   [175 176]]

  [[181 182]
   [187 188]
   [193 194]
   [199 200]
   [205 206]]

  [[211 212]
   [217 218]
   [223 224]
   [229 230]
   [235 236]]]


 [[[241 242]
   [247 248]
   [253 254]
   [259 260]
   [265 266]]

  [[271 272]
   [277 278]
   [283 284]
   [289 290]
   [295 296]]

  [[301 302]
   [307 308]
   [313 314]
   [319 320]
   [325 326]]

  [[331 332]
   [337 338]
   [343 344]
   [349 350]
   [355 356]]]]


In [165]:
(a[0, ..., 1:3]).shape

(3, 4, 5, 2)

In [166]:
a * 3

array([[[[[   0,    3,    6,    9,   12,   15],
          [  18,   21,   24,   27,   30,   33],
          [  36,   39,   42,   45,   48,   51],
          [  54,   57,   60,   63,   66,   69],
          [  72,   75,   78,   81,   84,   87]],

         [[  90,   93,   96,   99,  102,  105],
          [ 108,  111,  114,  117,  120,  123],
          [ 126,  129,  132,  135,  138,  141],
          [ 144,  147,  150,  153,  156,  159],
          [ 162,  165,  168,  171,  174,  177]],

         [[ 180,  183,  186,  189,  192,  195],
          [ 198,  201,  204,  207,  210,  213],
          [ 216,  219,  222,  225,  228,  231],
          [ 234,  237,  240,  243,  246,  249],
          [ 252,  255,  258,  261,  264,  267]],

         [[ 270,  273,  276,  279,  282,  285],
          [ 288,  291,  294,  297,  300,  303],
          [ 306,  309,  312,  315,  318,  321],
          [ 324,  327,  330,  333,  336,  339],
          [ 342,  345,  348,  351,  354,  357]]],


        [[[ 360,  363,  366,  